cmake_minimum_required(VERSION 3.16)
project(pct_planner)
find_package(ament_cmake REQUIRED)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_INSTALL_RPATH "$ORIGIN")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
add_subdirectory(planner/lib)
install(TARGETS a_star ele_planner traj_opt py_map_manager a_star_search ele_planner_lib gpmp_optimizer map_manager common_smoothing LIBRARY DESTINATION share/${PROJECT_NAME}/planner/lib)
install(DIRECTORY planner/scripts planner/config DESTINATION share/${PROJECT_NAME}/planner)
install(DIRECTORY tomography src DESTINATION share/${PROJECT_NAME})
install(PROGRAMS launchers/pct_plan launchers/pct_tomography DESTINATION lib/${PROJECT_NAME})
ament_package()
