traj_server:
  ros__parameters:
    traj_server.time_forward: 2.0
    traj_server.kp_position: 0.8
    traj_server.odom_timeout: 0.5
    use_sim_time: false
ego_planner_node:
  ros__parameters:
    fsm.flight_type: 3
    fsm.thresh_replan: 0.5
    fsm.thresh_no_replan: 0.1
    fsm.planning_horizen_time: 2.0
    fsm.emergency_time_: 1.0
    fsm.waypoint_num: 5
    fsm.waypoint0_x: -15.0
    fsm.waypoint0_y: 0.0
    fsm.waypoint0_z: 0.5
    fsm.waypoint1_x: 0.0
    fsm.waypoint1_y: 15.0
    fsm.waypoint1_z: 0.5
    fsm.waypoint2_x: 15.0
    fsm.waypoint2_y: 0.0
    fsm.waypoint2_z: 0.5
    fsm.waypoint3_x: 0.0
    fsm.waypoint3_y: -15.0
    fsm.waypoint3_z: 0.5
    fsm.waypoint4_x: -15.0
    fsm.waypoint4_y: 0.0
    fsm.waypoint4_z: 0.5
    grid_map.resolution: 0.1
    grid_map.local_update_range_x: 5.0
    grid_map.local_update_range_y: 5.0
    grid_map.local_update_range_z: 5.5
    grid_map.obstacles_inflation: 0.1
    grid_map.local_map_margin: 20
    grid_map.ground_height: -0.1
    grid_map.cx: 321.04638671875
    grid_map.cy: 243.44969177246094
    grid_map.fx: 387.229248046875
    grid_map.fy: 387.229248046875
    grid_map.use_depth_filter: true
    grid_map.depth_filter_tolerance: 0.15
    grid_map.depth_filter_maxdist: 5.0
    grid_map.depth_filter_mindist: 0.1
    grid_map.depth_filter_margin: 1
    grid_map.k_depth_scaling_factor: 1000.0
    grid_map.skip_pixel: 5
    grid_map.p_hit: 0.65
    grid_map.p_miss: 0.35
    grid_map.p_min: 0.12
    grid_map.p_max: 0.9
    grid_map.p_occ: 0.8
    grid_map.min_ray_length: 0.2
    grid_map.max_ray_length: 4.5
    grid_map.virtual_ceil_height: 50.5
    grid_map.visualization_truncate_height: 50.5
    grid_map.show_occ_time: false
    grid_map.pose_type: 2
    manager.max_jerk: 2.0
    manager.control_points_distance: 0.2
    manager.feasibility_tolerance: 0.3
    optimization.lambda_smooth: 1.0
    optimization.lambda_collision: 1.0
    optimization.lambda_feasibility: 0.1
    optimization.lambda_fitness: 5.0
    optimization.lambda_z_penalty: 1.2
    bspline.limit_ratio: 1.1
    use_sim_time: false
