#!/usr/bin/env python3
import os, runpy, sys
from ament_index_python.packages import get_package_share_directory
folder = os.path.join(get_package_share_directory('pct_planner'), 'tomography')
sys.path[:0] = [os.path.join(folder, 'scripts'), folder]
runpy.run_path(os.path.join(folder, 'scripts', 'tomography.py'), run_name='__main__')
